services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: addisonairsolution
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
